### ISSUE TITLE
Lesson Formatting

### ISSUE THREAD

**Issue by jaegpark** [IncendiumAcademy/just-the-docs#17]
### Include

- [x] lesson consistency so that hr's and br's are consistent with title/author spacing
- [x] add table of contents within each page for lessons that are written out
- [x] reformat video lessons so that title appears below the video container
- [x] resize video container so that it's at a more natural dimension size
- [x] consider adding overlay/bg colours like Khan academy

**Comment by jaegpark** [comment]
we should also include spoiler bars on the left hand side for solution dropdown
all of these are in the \<details> tag

**Comment by 0ffz** [comment]
I'll get started on the video one, will add an optional tag for yaml that lets you define a video URL which when present will show the video above title

**Comment by jaegpark** [comment]
@0ffz which branch are you working that on

**Comment by 0ffz** [comment]
Haven't started yet, but I think it's small enough I could just commit straight to master

**Comment by jaegpark** [comment]
kk
